apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: squid
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.0.242"
  externalTrafficPolicy: Local
  selector:
    app: squid
  ports:
    - port: 3128
      targetPort: 3128
      name: http-proxy
