apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perplexica
  namespace: perplexica
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: search.massivehog.win
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: perplexica
            port:
              number: 3000
  tls:
  - hosts:
    - search.massivehog.win
    secretName: perplexica-tls
